import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';

import '@/styles/globals.css';

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  preload: false,
  display: 'swap',
  fallback: ['Hiragino Sans', 'Hiragino Kaku Gothic ProN', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Next.js + Conform',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html
      lang="ja"
      className={notoSansJP.className}
    >
      <body className="">
        <main className="flex h-screen flex-col items-center justify-center space-y-2 bg-slate-200 tracking-tighter">
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
